### ISSUE TITLE
Css To React

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms-gildata/App001#8]
> Css To React

http://staxmanade.com/CssToReact/

```css
.font-color{
     color:red;
}
```

```js

{
    "font_color": {
        "color": "red"
    }
}

```
